"use client";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Bot } from "lucide-react";

interface ReviewCardProps {
  content: string;
}

export default function ReviewCard({ content }: ReviewCardProps) {
  const verdictMatch = content.match(/Verdict.*?:.*?(Accept|Reject|Weak Accept|Weak Reject)/i);
  const verdict = verdictMatch ? verdictMatch[1] : null;

  const getBadgeColor = (v: string | null) => {
    if (!v) return "bg-gray-500";
    if (v.toLowerCase().includes("accept")) return "bg-green-600";
    if (v.toLowerCase().includes("reject")) return "bg-red-600";
    return "bg-yellow-600";
  };

  return (
    <Card className="border-muted/50 shadow-sm overflow-hidden h-full">
      <CardHeader className="bg-muted/20 border-b pb-4">
        <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
                <div className="bg-purple-100 dark:bg-purple-900/30 p-2 rounded-lg text-purple-600 dark:text-purple-400">
                    <Sparkles className="h-5 w-5" />
                </div>
                <div>
                    <CardTitle className="text-lg">AI Peer Review</CardTitle>
                    <p className="text-xs text-muted-foreground flex items-center gap-1">
                        <Bot className="h-3 w-3" /> Generated by Gemini
                    </p>
                </div>
            </div>
            {verdict && (
                <Badge className={`${getBadgeColor(verdict)} text-white px-3 py-1`}>
                    {verdict}
                </Badge>
            )}
        </div>
      </CardHeader>
      
      <CardContent className="p-6 bg-background">
        <article className="prose prose-sm dark:prose-invert max-w-none break-words">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {content}
          </ReactMarkdown>
        </article>
      </CardContent>
    </Card>
  );
}